server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelMicro
    username: postgres
    password: vfire
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        
  application:
    name: HOTEL-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka   
    