server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://vfire:vfire@cluster0.kghip.mongodb.net/Microservices?retryWrites=true&w=majority
      
  application:
    name: RATING-SERVICE
    
  config:
    import: optional:configserver:http://localhost:8085