server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://vfire:vfire@cluster0.kghip.mongodb.net/Microservices?retryWrites=true&w=majority
      
  application:
    name: RATING-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      